<?php

namespace AW\AnimalsBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * AnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavouriteRepository extends EntityRepository
{
	public function getOrderedAnimals()
	{
	    return $this->createQueryBuilder('d')
	    ->addOrderBy('d.id', "DESC")
        ->getQuery()
        ->getResult()
	    ;
	}

}